name: Tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compose
        run: |
          docker compose version
          docker compose up
